# Generated by Django 3.0.6 on 2020-05-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_auto_20200506_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cocktail_category',
            new_name='Category',
        ),
    ]
