# Generated by Django 3.0.6 on 2020-05-06 17:32

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cocktails', '0003_auto_20200506_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_cocktail',
            name='cocktail',
        ),
        migrations.RemoveField(
            model_name='tag_cocktail',
            name='tag',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tag_cocktail',
        ),
    ]
