# Generated by Django 3.0.6 on 2020-05-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_auto_20200506_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='cocktails.Tip_category'),
        ),
    ]
