# Generated by Django 3.0.6 on 2020-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_auto_20200512_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='method',
            field=models.CharField(choices=[('Simple', 'S'), ('Sheyker required', 'H'), ('Blender required', 'B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
