# Generated by Django 3.0.6 on 2020-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200524_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='n_type',
            field=models.CharField(choices=[('Greetings', 'Greetings'), ('Info', 'Info'), ('NewFollower', 'NewFollower'), ('NewLike', 'NewLike'), ('NewComment', 'NewComment'), ('NewFollowerPost', 'NewFollowerPost'), ('NewFollowerTip', 'NewFollowerTip')], max_length=20),
        ),
    ]
